//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Tdesyat
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Посадочный талон.
    /// </summary>
    // *** Start programmer edit section *** (ПосадТалон CustomAttributes)

    // *** End programmer edit section *** (ПосадТалон CustomAttributes)
    [PublishName("Посадочный талон")]
    [AutoAltered()]
    [Caption("Посадочный талон")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ПосадТалонE", new string[] {
            "ДатаВыд as \'Дата выдачи\'",
            "Пассажир as \'Пассажир\'",
            "Пассажир.ФИО as \'ФИО\'",
            "Рейс.Откуда as \'Откуда\'",
            "Рейс.Куда as \'Куда\'",
            "Пассажир.МестоНаРейс.Класс as \'Класс\'",
            "Пассажир.МестоНаРейс.Место as \'Место\'",
            "Пассажир.КодБрони.Код as \'Код бронирования\'",
            "Рейс as \'Рейс\'",
            "Рейс.Дата as \'Дата\'",
            "Рейс.ВремяОтпр as \'Время отправления\'",
            "Рейс.НачПосад as \'Начало посадки\'",
            "Рейс.КонецПосад as \'Конец посадки\'",
            "Рейс.Выход"}, Hidden=new string[] {
            "Пассажир.ФИО",
            "Рейс.Куда"})]
    [MasterViewDefineAttribute("ПосадТалонE", "Пассажир", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "ФИО")]
    [MasterViewDefineAttribute("ПосадТалонE", "Рейс", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Куда")]
    [View("ПосадТалонL", new string[] {
            "ДатаВыд as \'Дата выдачи\'",
            "Пассажир.ФИО as \'ФИО\'",
            "Рейс.Куда as \'Куда\'"})]
    public class ПосадТалон : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fДатаВыд = System.DateTime.Parse("UtcNow=Now");
        
        private IIS.Tdesyat.Пассажир fПассажир;
        
        private IIS.Tdesyat.Рейс fРейс;
        
        // *** Start programmer edit section *** (ПосадТалон CustomMembers)

        // *** End programmer edit section *** (ПосадТалон CustomMembers)

        
        /// <summary>
        /// ДатаВыд.
        /// </summary>
        // *** Start programmer edit section *** (ПосадТалон.ДатаВыд CustomAttributes)

        // *** End programmer edit section *** (ПосадТалон.ДатаВыд CustomAttributes)
        public virtual System.DateTime ДатаВыд
        {
            get
            {
                // *** Start programmer edit section *** (ПосадТалон.ДатаВыд Get start)

                // *** End programmer edit section *** (ПосадТалон.ДатаВыд Get start)
                System.DateTime result = this.fДатаВыд;
                // *** Start programmer edit section *** (ПосадТалон.ДатаВыд Get end)

                // *** End programmer edit section *** (ПосадТалон.ДатаВыд Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПосадТалон.ДатаВыд Set start)

                // *** End programmer edit section *** (ПосадТалон.ДатаВыд Set start)
                this.fДатаВыд = value;
                // *** Start programmer edit section *** (ПосадТалон.ДатаВыд Set end)

                // *** End programmer edit section *** (ПосадТалон.ДатаВыд Set end)
            }
        }
        
        /// <summary>
        /// Посадочный талон.
        /// </summary>
        // *** Start programmer edit section *** (ПосадТалон.Пассажир CustomAttributes)

        // *** End programmer edit section *** (ПосадТалон.Пассажир CustomAttributes)
        [PropertyStorage(new string[] {
                "Пассажир"})]
        [NotNull()]
        public virtual IIS.Tdesyat.Пассажир Пассажир
        {
            get
            {
                // *** Start programmer edit section *** (ПосадТалон.Пассажир Get start)

                // *** End programmer edit section *** (ПосадТалон.Пассажир Get start)
                IIS.Tdesyat.Пассажир result = this.fПассажир;
                // *** Start programmer edit section *** (ПосадТалон.Пассажир Get end)

                // *** End programmer edit section *** (ПосадТалон.Пассажир Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПосадТалон.Пассажир Set start)

                // *** End programmer edit section *** (ПосадТалон.Пассажир Set start)
                this.fПассажир = value;
                // *** Start programmer edit section *** (ПосадТалон.Пассажир Set end)

                // *** End programmer edit section *** (ПосадТалон.Пассажир Set end)
            }
        }
        
        /// <summary>
        /// Посадочный талон.
        /// </summary>
        // *** Start programmer edit section *** (ПосадТалон.Рейс CustomAttributes)

        // *** End programmer edit section *** (ПосадТалон.Рейс CustomAttributes)
        [PropertyStorage(new string[] {
                "Рейс"})]
        [NotNull()]
        public virtual IIS.Tdesyat.Рейс Рейс
        {
            get
            {
                // *** Start programmer edit section *** (ПосадТалон.Рейс Get start)

                // *** End programmer edit section *** (ПосадТалон.Рейс Get start)
                IIS.Tdesyat.Рейс result = this.fРейс;
                // *** Start programmer edit section *** (ПосадТалон.Рейс Get end)

                // *** End programmer edit section *** (ПосадТалон.Рейс Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПосадТалон.Рейс Set start)

                // *** End programmer edit section *** (ПосадТалон.Рейс Set start)
                this.fРейс = value;
                // *** Start programmer edit section *** (ПосадТалон.Рейс Set end)

                // *** End programmer edit section *** (ПосадТалон.Рейс Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ПосадТалонE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПосадТалонE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПосадТалонE", typeof(IIS.Tdesyat.ПосадТалон));
                }
            }
            
            /// <summary>
            /// "ПосадТалонL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПосадТалонL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПосадТалонL", typeof(IIS.Tdesyat.ПосадТалон));
                }
            }
        }
    }
}
